### ISSUE TITLE
💥 [DevOps] Release v2.0.X – Groups Etc.

### ISSUE THREAD

**Issue by Tirokk** [wir-social/freilernen-social#8]
## 💥 DevOps Ticket

Release v2.0.X – groups etc.

### Todo

- [ ] do we like to have hidden groups?
- [ ] change logo, see below
- [ ] set internal pages correct with @sushidave 
- [ ] correct `locale` cookie exploration date in data privacy

#### New Logo

Was to big to upload here: aks @Tirokk
